---
- name: Find brew command
  ansible.builtin.shell: |
    if [ -x /usr/local/bin/brew ]; then
      echo /usr/local/bin/brew;
    elif [ -x /opt/homebrew/bin/brew ]; then
      echo /opt/homebrew/bin/brew;
    else
      exit 1;
    fi
  register: brew_path
  changed_when: false
  tags:
    - colima

- name: Launch colima now and at boot/login
  ansible.builtin.command: "{{ brew_path.stdout.strip() }} services start colima"
  become: true
  become_user: "{{ colima_user }}"
  changed_when: false
  tags:
    - colima
